services:
  web:
    build: ./web
    ports:
      - "3300:3000"
    networks:
      - good_onyx_internal
      - good_onyx_public
    restart: unless-stopped
  server:
    build: ./server
    ports:
      - "4444:4000"
    mem_limit: 2G
    restart: unless-stopped
    networks:
      - good_onyx_internal
      - good_onyx_public
  playwright:
    build: ./playwright
    mem_limit: 2G
    restart: unless-stopped
    ports:
      - "6666:6666"
    networks:
      - good_onyx_internal
      - good_onyx_public
      
networks:
  good_onyx_internal:
    driver: bridge
  good_onyx_public:
    external: true


