services:
  web:
    build: ./web
    ports:
      - "3300:3000"
    environment:
      - BASE_SERVER_URL=http://server:4000
      - NEXT_PUBLIC_BASE_SERVER_URL=http://server:4000
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/postgres
      - MIGRATE=true
    networks:
      - good_onyx_internal
      - good_onyx_public
    restart: unless-stopped
  server:
    build: ./server
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/postgres
      - MIGRATE=true
    ports:
      - "4000:4000"
    mem_limit: 2G
    restart: unless-stopped
    networks:
      - good_onyx_internal
  db:
    image: postgres:17.2-bullseye
    networks:
      - good_onyx_internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  keydb:
    image: eqalpha/keydb
    networks:
      - good_onyx_internal
    volumes:
      - keydb_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
networks:
  good_onyx_internal:
    driver: bridge
  good_onyx_public:
    external: true

volumes:
  postgres_data:
  keydb_data:


