services:
  prod-db: 
    image: postgres:17.5-alpine
    ports:
      - 5545:5432
    restart: unless-stopped
    env_file: ./.env.postgres-prod
    volumes:
      - ./postgres-data-prod:/var/lib/postgresql/data
    networks:
      - good_onyx_internal
      - good_onyx_public
  dev-db:
    image: postgres:17.5-alpine
    ports:
      - 5544:5432
    restart: unless-stopped
    env_file: ./.env.postgres-dev
    volumes:
      - ./postgres-data-dev:/var/lib/postgresql/data
    networks:
      - good_onyx_internal
      - good_onyx_public
  keydb:
    image: eqalpha/keydb
    networks:
      - good_onyx_internal
      - good_onyx_public
    volumes:
      - keydb_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
  socketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    networks:
      - good_onyx_internal
      - good_onyx_public
    ports:
      - "6001:6001"
      - "9601:9601"
    restart: unless-stopped
    environment:
      SOKETI_DB_REDIS_HOST: "keydb"
      SOKETI_DB_REDIS_PORT: 6379
      
networks:
  good_onyx_internal:
    driver: bridge
  good_onyx_public:
    external: true

volumes:
  keydb_data:
