version: "3"

includes:
  docker: ./DockerTasks.yml
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  playwright:
    taskfile: ./playwright/Taskfile.yml
    dir: ./playwright
tasks:
  dev:
    deps: [web:dev, server:dev, playwright:dev]
  build:
    deps: [web:build, server:build, playwright:build]
  start:
    deps: [web:start, server:start, playwright:start]
  test:
    deps: [web:test, server:test, playwright:test]
  migrate:
    dir: server
    cmds:
      - npx drizzle-kit migrate
  deploy:
    cmds:
      - task: docker:deploy-dbs
      - task: migrate
      - task: docker:deploy-server
      - task: docker:deploy-web
  short-deploy:
    cmds:
      - task: migrate
      - task: docker:deploy-server
      - task: docker:deploy-web
      - task: docker:deploy-playwright
