version: "3"

includes:
  docker: ./DockerTasks.yml
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
tasks:
  dev:
    deps: [web:dev, server:dev]
  migrate:
    dir: web
    cmds:
      - npx drizzle-kit migrate
  deploy:
    cmds:
      - task: docker:deploy-dbs
      - task: migrate
      - task: docker:deploy-server
      - task: docker:deploy-web
