version: "3"

includes:
  docker: ./DockerTasks.yml
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web
  automator:
    taskfile: ./automator/Taskfile.yml
    dir: ./automator
tasks:
  dev:
    deps: [web:dev, automator:dev]
  migrate:
    dir: web
    cmds:
      - npx drizzle-kit migrate
  deploy:
    cmds:
      - task: docker:deploy-dbs
      - task: migrate
      - task: docker:deploy-automator
      - task: docker:deploy-web
