version: "3"

tasks:
  install:
    cmds:
      - npm install {{.CLI_ARGS}}
  dev:
    cmds:
      - npm run dev
  build:
    cmds:
      - npm run build
  start:
    cmds:
      - npm run start
  test:
    cmds:
      - npm run test