version: "3"

tasks:
  install:
    cmds:
      - npm install {{.CLI_ARGS}}
  dev:
    cmds:
      - npm run dev
  build:
    cmds:
      - npm run build
      - cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/
  start:
    cmds:
      - npm run start
  test:
    cmds:
      - npm run test
